name: nice_counter_app
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  intl: ^0.17.0
  simple_animations: ^3.1.1
  flare_flutter: ^3.0.0
  hydrated_bloc: ^7.0.1
  path_provider: ^2.0.2
  animate_do: ^2.0.0
  device_preview: ^0.7.3
  sizer: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.0
  mocktail: ^0.1.0
  very_good_analysis: ^2.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/flares/
